NumPy for AI/ML - Assignment
Name : Mounika Parasa

Conceptual Understanding


A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons?

* Numpy arrays preffered because of mainly for faster computation means used to fast and easy numerical caluclations than python lists.
Numpy arrays are efficient for numerical caluclations,which is useful for larger datasets.

A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets? 

* Vectorized means performing an operation on an entire numpy array at once without using loops we can perform operations.

Because of 
* Vectorized numpy operations are much faster than python loops.
* They reduce execution time and are more efficient for larger datasets.

A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each?

* A*B -> Performs multiplication by element wise , with each element of A is mutiplied by the corresponding element of B.
* Nueral-network situation is Image filtering: Used to apply a mask to an image, such as highlighting or hiding specific areas
* A@B -> Perforns matrix multiplication means rows of A multiplied with columns of B.
* Neural-network situation is Face recognition: Used to multiply input features by trained weights to recognize a face.

What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise. 
* 
Broadcasting allows NumPy to perform element-wise operations on arrays with different dimensions of arrays.


In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = 10
print(a+b)

[11 12 13]


Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?
Answer:
flatten() returns a copy of the array, we doesnt change original after modifying of copy.(flatten = copy)
ravel() usually returns a view of the original array when possible, original one also be changed.(ravel = view)
For a memory-constrained application, I would prefer ravel() because it generally uses less additional memory.
         ravel() is preferred for large images because it can avoid creating an unnecessary copy.



A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example?
* axis=0 → performs the operation column-wise.
axis=1 → performs the operation row-wise.


In [4]:
#For a 2D array:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
#column wise
np.sum(A, axis=0) 


array([5, 7, 9])

In [5]:
#row wise
np.sum(A, axis=1)

array([ 6, 15])

A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.
Answer:
Normalization and standardization bring features to comparable scales, preventing features with large numerical values from dominating the model.
Normalization: Usually scales values to a fixed range such as 0 to 1.
Standardization: Transforms values to have mean 0 and standard deviation 1.

A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN? 

Answer:
np.nanmean() calculates the mean while ignoring NaN (missing) values.
If np.mean() is used directly on data containing NaN, the result is usually NaN.


In [7]:
a = np.array([10, 20, np.nan, 40])

print(np.nanmean(a))

23.333333333333332


A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128. 
X.shape = (samples, features)
For RGB images, each image has 3 color channels: Red, Green, and Blue.
For 64 RGB images of size 128 × 128, the exact shape is:
(64, 128, 128, 3)

A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed). 
Answer:
Reproducibility means getting the same results when the same experiment is repeated. Random operations can produce different results each time, so fixing a random seed makes experiments consistent.


In [1]:
import numpy as np

rng = np.random.default_rng(42)
print(rng.random(3))

[0.77395605 0.43887844 0.85859792]


B1. Predict the exact output and/or resulting shape. Justify in one sentence. 
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

i think a looks like 1 row and 3 columns  means shape is (3,)and array b is of 3rows and 1 column (3,1).
according to broadcasting addition performs on different dimensions of arrays so 
predicted output is (3, 3)



B2. Predict the output and/or shape. 
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

2nd column -> 2,5
* predicted output is:
[2 5]


B3. Predict the output and/or shape. 
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

It selects only of which are to be divisible by 10
* predicted output is
[10 20]


B4. Predict the output and/or shape. 
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)

it transpose matrix and multiply with the original matrix
* [[10 14]
[14 20]]

Questions B5–B8
B5. Predict the output and/or shape. 
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

output:
nan 2.3333333333335

B6. Predict the output and/or shape. 
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

output:
[0 1 1]

B7. Predict the output and/or shape. 
a = np.zeros((3, 4))
print(a.ndim, a.size)
It gives no.of dimensions
* Output:
2 12


B8. Predict the output and/or shape. 
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])
Output:
[[12 11 10 9]
[8 7 6 5]
[4 3 2 1]]



In [3]:

#C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). 

import numpy as np

scores = np.array([35, 42, 67, 28, 50])

result = np.where(scores >= 40, "P", "F")

print(result)

['F' 'P' 'P' 'F' 'P']


In [4]:
#C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. 
import numpy as np

def standardize(x):
    return (x - np.mean(x)) / np.std(x)

x = np.array([10, 20, 30, 40, 50])

print(standardize(x))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [5]:
#C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

combined = np.vstack((A, B))

print(combined)
print(combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [6]:
#C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression
import numpy as np

X = np.random.rand(100, 5)

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print(mean)
print(std)
print(X_standardized.shape)

[0.49093657 0.46353188 0.52988796 0.46806632 0.51092374]
[0.29107515 0.28924677 0.29248957 0.29518253 0.27857899]
(100, 5)


In [7]:
#C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true. 
import numpy as np

X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

w = np.array([0.5, 1.0])
b = 2

y_true = np.array([4, 6, 8])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [ 4.5  7.5 10.5]
MSE: 2.9166666666666665


In [8]:
#C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed. 
import numpy as np

rng = np.random.default_rng(42)

X1 = rng.normal(size=(10, 3))
print("Shape:", X1.shape)

rng = np.random.default_rng(42)
X2 = rng.normal(size=(10, 3))

print("Identical:", np.array_equal(X1, X2))

Shape: (10, 3)
Identical: True


In [9]:
#C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization. 
import numpy as np

image = np.array([[0, 64],
                  [128, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

[[0.         0.25098039]
 [0.50196078 1.        ]]


In [10]:

#C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why. 
import numpy as np

images = np.random.rand(4, 28, 28, 3)

avg_pixel = np.mean(images, axis=(1, 2, 3))

print(avg_pixel)
print(avg_pixel.shape)

[0.50342107 0.50159905 0.49874581 0.49921373]
(4,)


In [11]:
#D1. Data Preprocessing Pipeline 
#You are given a raw 1D or 2D NumPy array containing NaN values.
#Describe, step by step, the NumPy operations you would apply to:
#(a) detect missing values,
#(b) handle them appropriately and justify your strategy, and
#(c) normalize or standardize the clean data before it is fed to a model.

#Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.



import numpy as np

data = np.array([
    [10.0, 20.0],
    [15.0, np.nan],
    [20.0, 30.0],
    [25.0, 40.0]
])

# Step 1: Detect missing values
missing = np.isnan(data)
print("Missing values:")
print(missing)

# Step 2: Replace NaN values with column means
column_means = np.nanmean(data, axis=0)
data_clean = np.where(missing, column_means, data)

print("Clean data:")
print(data_clean)

# Step 3: Standardize the clean data
mean = np.mean(data_clean, axis=0)
std = np.std(data_clean, axis=0)

standardized = (data_clean - mean) / std

print("Standardized data:")
print(standardized)

Missing values:
[[False False]
 [False  True]
 [False False]
 [False False]]
Clean data:
[[10. 20.]
 [15. 30.]
 [20. 30.]
 [25. 40.]]
Standardized data:
[[-1.34164079 -1.41421356]
 [-0.4472136   0.        ]
 [ 0.4472136   0.        ]
 [ 1.34164079  1.41421356]]


In [15]:
 

#1.Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.
#A single rgb image has shape
(64,64,3)



(64, 64, 3)

In [16]:

#Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

import numpy as np

images = np.random.randint(0, 256, size=(16, 64, 64, 3))

print(images.shape)

(16, 64, 64, 3)


In [ ]:
#Compute the average image of the batch, meaning the element-wise mean across all 16 images.


In [ ]:
#

In [17]:
#the corrected code.
import numpy as np

X = np.array([[1,2],[2,3],[3,4]])
w = np.array([0.5,1.0])
b = 2.0

y_pred = X @ w + b
y_true = np.array([10,20,30])

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


In [ ]:
#Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns




In [ ]:
#Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:
#Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).
#Hint: You may need to nest or combine np.where() calls.

